export const rankList = [
  // Officer Grades (O10 - O1)
  { label: 'O10', value: 'O10' },
  { label: 'O9', value: 'O9' },
  { label: 'O8', value: 'O8' },
  { label: 'O7', value: 'O7' },
  { label: 'O6', value: 'O6' },
  { label: 'O5', value: 'O5' },
  { label: 'O4', value: 'O4' },
  { label: 'O3', value: 'O3' },
  { label: 'O2', value: 'O2' },
  { label: 'O1', value: 'O1' },

  // Enlisted Grades (E9 - E1)
  { label: 'E9', value: 'E9' },
  { label: 'E8', value: 'E8' },
  { label: 'E7', value: 'E7' },
  { label: 'E6', value: 'E6' },
  { label: 'E5', value: 'E5' },
  { label: 'E4', value: 'E4' },
  { label: 'E3', value: 'E3' },
  { label: 'E2', value: 'E2' },
  { label: 'E1', value: 'E1' },

  // Salary Grades (SG24 - SG1)
  { label: 'SG24', value: 'SG24' },
  { label: 'SG23', value: 'SG23' },
  { label: 'SG22', value: 'SG22' },
  { label: 'SG21', value: 'SG21' },
  { label: 'SG20', value: 'SG20' },
  { label: 'SG19', value: 'SG19' },
  { label: 'SG18', value: 'SG18' },
  { label: 'SG17', value: 'SG17' },
  { label: 'SG16', value: 'SG16' },
  { label: 'SG15', value: 'SG15' },
  { label: 'SG14', value: 'SG14' },
  { label: 'SG13', value: 'SG13' },
  { label: 'SG12', value: 'SG12' },
  { label: 'SG11', value: 'SG11' },
  { label: 'SG10', value: 'SG10' },
  { label: 'SG9', value: 'SG9' },
  { label: 'SG8', value: 'SG8' },
  { label: 'SG7', value: 'SG7' },
  { label: 'SG6', value: 'SG6' },
  { label: 'SG5', value: 'SG5' },
  { label: 'SG4', value: 'SG4' },
  { label: 'SG3', value: 'SG3' },
  { label: 'SG2', value: 'SG2' },
  { label: 'SG1', value: 'SG1' }
]

